Running suite(s): Default
98%: Checks: 54, Failures: 1, Errors: 0
public.c:211:F:Public:A_Array_sum:0: Assertion 'run_main("int arr[3]; def int main() { int sum; arr[0] = 1; arr[1] = 2; arr[2] = 3; " "sum = arr[0] + arr[1] + arr[2]; " "return sum;}") == 6' failed: run_main("int arr[3]; def int main() { int sum; arr[0] = 1; arr[1] = 2; arr[2] = 3; " "sum = arr[0] + arr[1] + arr[2]; " "return sum;}") == -9999, 6 == 6
